name: Continuous deployment

# Build on every branch push, tag push, and pull request change:
on: [push, pull_request]

env:
  RUSTFLAGS: "-D warnings"
  RUSTDOCFLAGS: "-D warnings"

jobs:
  check_fmt:
    name: Check format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout reposistory
        uses: actions/checkout@main

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Setup rustfmt
        run: rustup component add rustfmt

      - name: Check format
        run: cargo fmt -p g2dem-web --check

  check_clippy:
    name: Check clippy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout reposistory
        uses: actions/checkout@main

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Setup clippy
        run: rustup component add clippy

      - name: Run clippy
        run: cargo clippy -p g2dem-web --all-targets

  run_tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout reposistory
        uses: actions/checkout@main

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Run tests
        run: cargo test -p g2dem-web

  msrv:
    name: Check MSRV is correct
    runs-on: ubuntu-latest
    steps:
      - name: Checkout reposistory
        uses: actions/checkout@main

      - name: Setup MSRV checker
        uses: taiki-e/install-action@cargo-hack

      - name: Run MSRV checker
        run: cargo hack check -p g2dem-web --rust-version --workspace --all-targets --ignore-private

  deploy_g2dem_web:
    name: Deploy g2dem-web to Github Pages
    runs-on: ubuntu-latest
    # needs:
    #   - check_fmt
    #   - check_clippy
    #   - run_tests
    #   - msrv
    steps:
      - name: Checkout reposistory
        uses: actions/checkout@main

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Setup trunk
        uses: jetli/trunk-action@main
        with:
          version: 'latest'

      - name: debug
        run: |
          # cargo --version
          echo "$CARGO_HOME"
          # cargo --list --verbose
          echo "$PWD"


      # TODO: just testing, please remember to remove this step
      - name: Build g2dem-web with cargo
        run: |
          cargo build --release --locked --target=wasm32-unknown-unknown -p g2dem-web

      - name: Build g2dem-web
        run: |
          cd src/g2dem-web && trunk build --release --locked --public-url /${{ github.event.repository.name }} && cd ../..

      - name: Deployment
        uses: peaceiris/actions-gh-pages@v4
        # Only deploy in main branch
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src/g2dem-web/dist
